name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Set up Limesuite
      run: |
        sudo add-apt-repository -y ppa:myriadrf/drivers
        sudo apt-get -y update
        sudo apt-get install limesuite liblimesuite-dev

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
