name: Release Arm64

on:
  push:
    tags:
      - v*

jobs:

  build-arm64:
    runs-on: ubuntu-latest
    container: racerxdl/gocross:arm64
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        cd cmd
        go build -o lms_tcp_arm64

    - uses: actions/upload-artifact@v1
      name: "Upload artifacts"
      with:
        name: lms_tcp_armhf
        path: cmd/lms_tcp_arm64

    - name: Test
      run: go test -v ./...

    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.2.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        file: cmd/lms_tcp_arm64